apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: feast
stringData:
  POSTGRES_DB: feast
  POSTGRES_USER: feast
  POSTGRES_PASSWORD: feast
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: feast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        runAsUser: 999
        fsGroup: 999
        runAsNonRoot: true
      containers:
        - name: postgres
          image: 'pgvector/pgvector:pg18-trixie'
          ports:
            - containerPort: 5432
          envFrom:
          - secretRef:
              name: postgres-secret
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - |
                    sleep 2
                    until pg_isready -U feast; do sleep 1; done
                    psql -U feast -d feast -tc "SELECT 1 FROM pg_roles WHERE rolname='postgres'" | grep -q 1 || psql -U feast -d feast -c "CREATE ROLE postgres WITH SUPERUSER LOGIN;"
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: postgresdata
      volumes:
        - name: postgresdata
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: feast
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres